Update build-staging-deploy-s3.yml added if statement to check the bug

diff --git a/.github/workflows/build-staging-deploy-s3.yml b/.github/workflows/build-staging-deploy-s3.yml
--- a/.github/workflows/build-staging-deploy-s3.yml
+++ b/.github/workflows/build-staging-deploy-s3.yml
@@ -45,7 +45,9 @@ jobs:
           PREVIEW_BUCKET="preview-bucket-${PR_NUMBER}-${TIMESTAMP}"
           REGION=$(aws configure get region)
           echo "Creating bucket $PREVIEW_BUCKET in region $REGION"
-          aws s3api create-bucket --bucket $PREVIEW_BUCKET --region $REGION
+          if ! aws s3api create-bucket --bucket $PREVIEW_BUCKET --region $REGION 2>&1; then
+            echo "Error creating bucket!"
+          fi
           echo "Preview bucket created: ${PREVIEW_BUCKET}"
 
       - name: Deploy to S3
